#!/usr/bin/bash

LINES=$(tail -n +2 Electric_Vehicle_Population_Data.csv | wc -l | awk '{print $1}')
printf "%-50s %7s %11s 	\n" "Columna" "Distintos" "Porcentaje"
DISTINCT=$(tail -n +2 Electric_Vehicle_Population_Data.csv | cut -d\; -f1 | sort | uniq | wc -l  ); PERCENT=$(bc <<< "scale=4; $DISTINCT / $LINES * 100"); COLUMN=$(head -1 Electric_Vehicle_Population_Data.csv | cut -d\; -f1); printf "%-50s %10d %11.3f \n" $COLUMN $DISTINCT $PERCENT 
DISTINCT=$(tail -n +2 Electric_Vehicle_Population_Data.csv | cut -d\; -f2 | sort | uniq | wc -l  ); PERCENT=$(bc <<< "scale=4; $DISTINCT / $LINES * 100"); COLUMN=$(head -1 Electric_Vehicle_Population_Data.csv | cut -d\; -f2); printf "%-50s %10d %11.3f \n" $COLUMN $DISTINCT $PERCENT 
DISTINCT=$(tail -n +2 Electric_Vehicle_Population_Data.csv | cut -d\; -f3 | sort | uniq | wc -l  ); PERCENT=$(bc <<< "scale=4; $DISTINCT / $LINES * 100"); COLUMN=$(head -1 Electric_Vehicle_Population_Data.csv | cut -d\; -f3); printf "%-50s %10d %11.3f \n" $COLUMN $DISTINCT $PERCENT 
DISTINCT=$(tail -n +2 Electric_Vehicle_Population_Data.csv | cut -d\; -f4 | sort | uniq | wc -l  ); PERCENT=$(bc <<< "scale=4; $DISTINCT / $LINES * 100"); COLUMN=$(head -1 Electric_Vehicle_Population_Data.csv | cut -d\; -f4); printf "%-50s %10d %11.3f \n" $COLUMN $DISTINCT $PERCENT 
DISTINCT=$(tail -n +2 Electric_Vehicle_Population_Data.csv | cut -d\; -f5 | sort | uniq | wc -l  ); PERCENT=$(bc <<< "scale=4; $DISTINCT / $LINES * 100"); COLUMN=$(head -1 Electric_Vehicle_Population_Data.csv | cut -d\; -f5); printf "%-50s %10d %11.3f \n" $COLUMN $DISTINCT $PERCENT 
DISTINCT=$(tail -n +2 Electric_Vehicle_Population_Data.csv | cut -d\; -f6 | sort | uniq | wc -l  ); PERCENT=$(bc <<< "scale=4; $DISTINCT / $LINES * 100"); COLUMN=$(head -1 Electric_Vehicle_Population_Data.csv | cut -d\; -f6); printf "%-50s %10d %11.3f \n" $COLUMN $DISTINCT $PERCENT 
DISTINCT=$(tail -n +2 Electric_Vehicle_Population_Data.csv | cut -d\; -f7 | sort | uniq | wc -l  ); PERCENT=$(bc <<< "scale=4; $DISTINCT / $LINES * 100"); COLUMN=$(head -1 Electric_Vehicle_Population_Data.csv | cut -d\; -f7); printf "%-50s %10d %11.3f \n" $COLUMN $DISTINCT $PERCENT 
DISTINCT=$(tail -n +2 Electric_Vehicle_Population_Data.csv | cut -d\; -f8 | sort | uniq | wc -l  ); PERCENT=$(bc <<< "scale=4; $DISTINCT / $LINES * 100"); COLUMN=$(head -1 Electric_Vehicle_Population_Data.csv | cut -d\; -f8); printf "%-50s %10d %11.3f \n" $COLUMN $DISTINCT $PERCENT 
DISTINCT=$(tail -n +2 Electric_Vehicle_Population_Data.csv | cut -d\; -f9 | sort | uniq | wc -l  ); PERCENT=$(bc <<< "scale=4; $DISTINCT / $LINES * 100"); COLUMN=$(head -1 Electric_Vehicle_Population_Data.csv | cut -d\; -f9); printf "%-50s %10d %11.3f \n" $COLUMN $DISTINCT $PERCENT 
DISTINCT=$(tail -n +2 Electric_Vehicle_Population_Data.csv | cut -d\; -f10 | sort | uniq | wc -l  );PERCENT=$(bc <<< "scale=4; $DISTINCT / $LINES * 100"); COLUMN=$(head -1 Electric_Vehicle_Population_Data.csv | cut -d\; -f10); printf "%-50s %10d %11.3f \n" $COLUMN $DISTINCT $PERCENT 
DISTINCT=$(tail -n +2 Electric_Vehicle_Population_Data.csv | cut -d\; -f11 | sort | uniq | wc -l  );PERCENT=$(bc <<< "scale=4; $DISTINCT / $LINES * 100"); COLUMN=$(head -1 Electric_Vehicle_Population_Data.csv | cut -d\; -f11); printf "%-50s %10d %11.3f \n" $COLUMN $DISTINCT $PERCENT 
DISTINCT=$(tail -n +2 Electric_Vehicle_Population_Data.csv | cut -d\; -f12 | sort | uniq | wc -l  );PERCENT=$(bc <<< "scale=4; $DISTINCT / $LINES * 100"); COLUMN=$(head -1 Electric_Vehicle_Population_Data.csv | cut -d\; -f12); printf "%-50s %10d %11.3f \n" $COLUMN $DISTINCT $PERCENT 
DISTINCT=$(tail -n +2 Electric_Vehicle_Population_Data.csv | cut -d\; -f13 | sort | uniq | wc -l  );PERCENT=$(bc <<< "scale=4; $DISTINCT / $LINES * 100"); COLUMN=$(head -1 Electric_Vehicle_Population_Data.csv | cut -d\; -f13); printf "%-50s %10d %11.3f \n" $COLUMN $DISTINCT $PERCENT 
DISTINCT=$(tail -n +2 Electric_Vehicle_Population_Data.csv | cut -d\; -f14 | sort | uniq | wc -l  );PERCENT=$(bc <<< "scale=4; $DISTINCT / $LINES * 100"); COLUMN=$(head -1 Electric_Vehicle_Population_Data.csv | cut -d\; -f14); printf "%-50s %10d %11.3f \n" $COLUMN $DISTINCT $PERCENT 
DISTINCT=$(tail -n +2 Electric_Vehicle_Population_Data.csv | cut -d\; -f15 | sort | uniq | wc -l  );PERCENT=$(bc <<< "scale=4; $DISTINCT / $LINES * 100"); COLUMN=$(head -1 Electric_Vehicle_Population_Data.csv | cut -d\; -f15); printf "%-50s %10d %11.3f \n" $COLUMN $DISTINCT $PERCENT 
DISTINCT=$(tail -n +2 Electric_Vehicle_Population_Data.csv | cut -d\; -f16 | sort | uniq | wc -l  );PERCENT=$(bc <<< "scale=4; $DISTINCT / $LINES * 100"); COLUMN=$(head -1 Electric_Vehicle_Population_Data.csv | cut -d\; -f16); printf "%-50s %10d %11.3f \n" $COLUMN $DISTINCT $PERCENT 
DISTINCT=$(tail -n +2 Electric_Vehicle_Population_Data.csv | cut -d\; -f17 | sort | uniq | wc -l  );PERCENT=$(bc <<< "scale=4; $DISTINCT / $LINES * 100"); COLUMN=$(head -1 Electric_Vehicle_Population_Data.csv | cut -d\; -f17); printf "%-50s %10d %11.3f \n" $COLUMN $DISTINCT $PERCENT 

