#!/usr/bin/bash
#LINES=$(wc -l Electric_Vehicle_Population_Data.csv | awk '{print $1}');DISTINCT=$(cut -d\; -f1 Electric_Vehicle_Population_Data.csv | uniq | wc -l  );PERCENT=$(bc <<< "scale=4; $DISTINCT / $LINES * 100"); echo "$(head -1 Electric_Vehicle_Population_Data.csv | cut -d\; -f1) tiene $DISTINCT valores distintos de un total de $LINES registros.Esto representa $PERCENT%" 
#LINES=$(wc -l Electric_Vehicle_Population_Data.csv | awk '{print $1}');DISTINCT=$(cut -d\; -f2 Electric_Vehicle_Population_Data.csv | uniq | wc -l  );PERCENT=$(bc <<< "scale=4; $DISTINCT / $LINES * 100"); echo "$(head -1 Electric_Vehicle_Population_Data.csv | cut -d\; -f2) tiene $DISTINCT valores distintos de un total de $LINES registros.Esto representa $PERCENT%" 
#LINES=$(wc -l Electric_Vehicle_Population_Data.csv | awk '{print $1}');DISTINCT=$(cut -d\; -f3 Electric_Vehicle_Population_Data.csv | uniq | wc -l  );PERCENT=$(bc <<< "scale=4; $DISTINCT / $LINES * 100"); echo "$(head -1 Electric_Vehicle_Population_Data.csv | cut -d\; -f3) tiene $DISTINCT valores distintos de un total de $LINES registros.Esto representa $PERCENT%" 
#LINES=$(wc -l Electric_Vehicle_Population_Data.csv | awk '{print $1}');DISTINCT=$(cut -d\; -f4 Electric_Vehicle_Population_Data.csv | uniq | wc -l  );PERCENT=$(bc <<< "scale=4; $DISTINCT / $LINES * 100"); echo "$(head -1 Electric_Vehicle_Population_Data.csv | cut -d\; -f4) tiene $DISTINCT valores distintos de un total de $LINES registros.Esto representa $PERCENT%" 
#LINES=$(wc -l Electric_Vehicle_Population_Data.csv | awk '{print $1}');DISTINCT=$(cut -d\; -f5 Electric_Vehicle_Population_Data.csv | uniq | wc -l  );PERCENT=$(bc <<< "scale=4; $DISTINCT / $LINES * 100"); echo "$(head -1 Electric_Vehicle_Population_Data.csv | cut -d\; -f5) tiene $DISTINCT valores distintos de un total de $LINES registros.Esto representa $PERCENT%" 
#LINES=$(wc -l Electric_Vehicle_Population_Data.csv | awk '{print $1}');DISTINCT=$(cut -d\; -f6 Electric_Vehicle_Population_Data.csv | uniq | wc -l  );PERCENT=$(bc <<< "scale=4; $DISTINCT / $LINES * 100"); echo "$(head -1 Electric_Vehicle_Population_Data.csv | cut -d\; -f6) tiene $DISTINCT valores distintos de un total de $LINES registros.Esto representa $PERCENT%" 
#LINES=$(wc -l Electric_Vehicle_Population_Data.csv | awk '{print $1}');DISTINCT=$(cut -d\; -f7 Electric_Vehicle_Population_Data.csv | uniq | wc -l  );PERCENT=$(bc <<< "scale=4; $DISTINCT / $LINES * 100"); echo "$(head -1 Electric_Vehicle_Population_Data.csv | cut -d\; -f7) tiene $DISTINCT valores distintos de un total de $LINES registros.Esto representa $PERCENT%" 
#LINES=$(wc -l Electric_Vehicle_Population_Data.csv | awk '{print $1}');DISTINCT=$(cut -d\; -f8 Electric_Vehicle_Population_Data.csv | uniq | wc -l  );PERCENT=$(bc <<< "scale=4; $DISTINCT / $LINES * 100"); echo "$(head -1 Electric_Vehicle_Population_Data.csv | cut -d\; -f8) tiene $DISTINCT valores distintos de un total de $LINES registros.Esto representa $PERCENT%" 
#LINES=$(wc -l Electric_Vehicle_Population_Data.csv | awk '{print $1}');DISTINCT=$(cut -d\; -f9 Electric_Vehicle_Population_Data.csv | uniq | wc -l  );PERCENT=$(bc <<< "scale=4; $DISTINCT / $LINES * 100"); echo "$(head -1 Electric_Vehicle_Population_Data.csv | cut -d\; -f9) tiene $DISTINCT valores distintos de un total de $LINES registros.Esto representa $PERCENT%" 
#LINES=$(wc -l Electric_Vehicle_Population_Data.csv | awk '{print $1}');DISTINCT=$(cut -d\; -f10 Electric_Vehicle_Population_Data.csv | uniq | wc -l  );PERCENT=$(bc <<< "scale=4; $DISTINCT / $LINES * 100"); echo "$(head -1 Electric_Vehicle_Population_Data.csv | cut -d\; -f10) tiene $DISTINCT valores distintos de un total de $LINES registros.Esto representa $PERCENT%" 
#LINES=$(wc -l Electric_Vehicle_Population_Data.csv | awk '{print $1}');DISTINCT=$(cut -d\; -f11 Electric_Vehicle_Population_Data.csv | uniq | wc -l  );PERCENT=$(bc <<< "scale=4; $DISTINCT / $LINES * 100"); echo "$(head -1 Electric_Vehicle_Population_Data.csv | cut -d\; -f11) tiene $DISTINCT valores distintos de un total de $LINES registros.Esto representa $PERCENT%" 
#LINES=$(wc -l Electric_Vehicle_Population_Data.csv | awk '{print $1}');DISTINCT=$(cut -d\; -f12 Electric_Vehicle_Population_Data.csv | uniq | wc -l  );PERCENT=$(bc <<< "scale=4; $DISTINCT / $LINES * 100"); echo "$(head -1 Electric_Vehicle_Population_Data.csv | cut -d\; -f12) tiene $DISTINCT valores distintos de un total de $LINES registros.Esto representa $PERCENT%" 
#LINES=$(wc -l Electric_Vehicle_Population_Data.csv | awk '{print $1}');DISTINCT=$(cut -d\; -f13 Electric_Vehicle_Population_Data.csv | uniq | wc -l  );PERCENT=$(bc <<< "scale=4; $DISTINCT / $LINES * 100"); echo "$(head -1 Electric_Vehicle_Population_Data.csv | cut -d\; -f13) tiene $DISTINCT valores distintos de un total de $LINES registros.Esto representa $PERCENT%" 
#LINES=$(wc -l Electric_Vehicle_Population_Data.csv | awk '{print $1}');DISTINCT=$(cut -d\; -f14 Electric_Vehicle_Population_Data.csv | uniq | wc -l  );PERCENT=$(bc <<< "scale=4; $DISTINCT / $LINES * 100"); echo "$(head -1 Electric_Vehicle_Population_Data.csv | cut -d\; -f14) tiene $DISTINCT valores distintos de un total de $LINES registros.Esto representa $PERCENT%" 
#LINES=$(wc -l Electric_Vehicle_Population_Data.csv | awk '{print $1}');DISTINCT=$(cut -d\; -f15 Electric_Vehicle_Population_Data.csv | uniq | wc -l  );PERCENT=$(bc <<< "scale=4; $DISTINCT / $LINES * 100"); echo "$(head -1 Electric_Vehicle_Population_Data.csv | cut -d\; -f15) tiene $DISTINCT valores distintos de un total de $LINES registros.Esto representa $PERCENT%" 
#LINES=$(wc -l Electric_Vehicle_Population_Data.csv | awk '{print $1}');DISTINCT=$(cut -d\; -f16 Electric_Vehicle_Population_Data.csv | uniq | wc -l  );PERCENT=$(bc <<< "scale=4; $DISTINCT / $LINES * 100"); echo "$(head -1 Electric_Vehicle_Population_Data.csv | cut -d\; -f16) tiene $DISTINCT valores distintos de un total de $LINES registros.Esto representa $PERCENT%" 
#LINES=$(wc -l Electric_Vehicle_Population_Data.csv | awk '{print $1}');DISTINCT=$(cut -d\; -f17 Electric_Vehicle_Population_Data.csv | uniq | wc -l  );PERCENT=$(bc <<< "scale=4; $DISTINCT / $LINES * 100"); echo "$(head -1 Electric_Vehicle_Population_Data.csv | cut -d\; -f17) tiene $DISTINCT valores distintos de un total de $LINES registros.Esto representa $PERCENT%" 


LINES=$(wc -l Electric_Vehicle_Population_Data.csv | awk '{print $1}')
printf "%-50s %7s %11s 	\n" "Columna" "Distintos" "Porcentaje"
DISTINCT=$(cut -d\; -f1 Electric_Vehicle_Population_Data.csv | sort | uniq | wc -l  ); PERCENT=$(bc <<< "scale=4; $DISTINCT / $LINES * 100"); COLUMN=$(head -1 Electric_Vehicle_Population_Data.csv | cut -d\; -f1); printf "%-50s %10d %11.3f \n" $COLUMN $DISTINCT $PERCENT 
DISTINCT=$(cut -d\; -f2 Electric_Vehicle_Population_Data.csv | sort | uniq | wc -l  ); PERCENT=$(bc <<< "scale=4; $DISTINCT / $LINES * 100"); COLUMN=$(head -1 Electric_Vehicle_Population_Data.csv | cut -d\; -f2); printf "%-50s %10d %11.3f \n" $COLUMN $DISTINCT $PERCENT 
DISTINCT=$(cut -d\; -f3 Electric_Vehicle_Population_Data.csv | sort | uniq | wc -l  ); PERCENT=$(bc <<< "scale=4; $DISTINCT / $LINES * 100"); COLUMN=$(head -1 Electric_Vehicle_Population_Data.csv | cut -d\; -f3); printf "%-50s %10d %11.3f \n" $COLUMN $DISTINCT $PERCENT 
DISTINCT=$(cut -d\; -f4 Electric_Vehicle_Population_Data.csv | sort | uniq | wc -l  ); PERCENT=$(bc <<< "scale=4; $DISTINCT / $LINES * 100"); COLUMN=$(head -1 Electric_Vehicle_Population_Data.csv | cut -d\; -f4); printf "%-50s %10d %11.3f \n" $COLUMN $DISTINCT $PERCENT 
DISTINCT=$(cut -d\; -f5 Electric_Vehicle_Population_Data.csv | sort | uniq | wc -l  ); PERCENT=$(bc <<< "scale=4; $DISTINCT / $LINES * 100"); COLUMN=$(head -1 Electric_Vehicle_Population_Data.csv | cut -d\; -f5); printf "%-50s %10d %11.3f \n" $COLUMN $DISTINCT $PERCENT 
DISTINCT=$(cut -d\; -f6 Electric_Vehicle_Population_Data.csv | sort | uniq | wc -l  ); PERCENT=$(bc <<< "scale=4; $DISTINCT / $LINES * 100"); COLUMN=$(head -1 Electric_Vehicle_Population_Data.csv | cut -d\; -f6); printf "%-50s %10d %11.3f \n" $COLUMN $DISTINCT $PERCENT 
DISTINCT=$(cut -d\; -f7 Electric_Vehicle_Population_Data.csv | sort | uniq | wc -l  ); PERCENT=$(bc <<< "scale=4; $DISTINCT / $LINES * 100"); COLUMN=$(head -1 Electric_Vehicle_Population_Data.csv | cut -d\; -f7); printf "%-50s %10d %11.3f \n" $COLUMN $DISTINCT $PERCENT 
DISTINCT=$(cut -d\; -f8 Electric_Vehicle_Population_Data.csv | sort | uniq | wc -l  ); PERCENT=$(bc <<< "scale=4; $DISTINCT / $LINES * 100"); COLUMN=$(head -1 Electric_Vehicle_Population_Data.csv | cut -d\; -f8); printf "%-50s %10d %11.3f \n" $COLUMN $DISTINCT $PERCENT 
DISTINCT=$(cut -d\; -f9 Electric_Vehicle_Population_Data.csv | sort | uniq | wc -l  ); PERCENT=$(bc <<< "scale=4; $DISTINCT / $LINES * 100"); COLUMN=$(head -1 Electric_Vehicle_Population_Data.csv | cut -d\; -f9); printf "%-50s %10d %11.3f \n" $COLUMN $DISTINCT $PERCENT 
DISTINCT=$(cut -d\; -f10 Electric_Vehicle_Population_Data.csv | sort | uniq | wc -l  );PERCENT=$(bc <<< "scale=4; $DISTINCT / $LINES * 100"); COLUMN=$(head -1 Electric_Vehicle_Population_Data.csv | cut -d\; -f10); printf "%-50s %10d %11.3f \n" $COLUMN $DISTINCT $PERCENT 
DISTINCT=$(cut -d\; -f11 Electric_Vehicle_Population_Data.csv | sort | uniq | wc -l  );PERCENT=$(bc <<< "scale=4; $DISTINCT / $LINES * 100"); COLUMN=$(head -1 Electric_Vehicle_Population_Data.csv | cut -d\; -f11); printf "%-50s %10d %11.3f \n" $COLUMN $DISTINCT $PERCENT 
DISTINCT=$(cut -d\; -f12 Electric_Vehicle_Population_Data.csv | sort | uniq | wc -l  );PERCENT=$(bc <<< "scale=4; $DISTINCT / $LINES * 100"); COLUMN=$(head -1 Electric_Vehicle_Population_Data.csv | cut -d\; -f12); printf "%-50s %10d %11.3f \n" $COLUMN $DISTINCT $PERCENT 
DISTINCT=$(cut -d\; -f13 Electric_Vehicle_Population_Data.csv | sort | uniq | wc -l  );PERCENT=$(bc <<< "scale=4; $DISTINCT / $LINES * 100"); COLUMN=$(head -1 Electric_Vehicle_Population_Data.csv | cut -d\; -f13); printf "%-50s %10d %11.3f \n" $COLUMN $DISTINCT $PERCENT 
DISTINCT=$(cut -d\; -f14 Electric_Vehicle_Population_Data.csv | sort | uniq | wc -l  );PERCENT=$(bc <<< "scale=4; $DISTINCT / $LINES * 100"); COLUMN=$(head -1 Electric_Vehicle_Population_Data.csv | cut -d\; -f14); printf "%-50s %10d %11.3f \n" $COLUMN $DISTINCT $PERCENT 
DISTINCT=$(cut -d\; -f15 Electric_Vehicle_Population_Data.csv | sort | uniq | wc -l  );PERCENT=$(bc <<< "scale=4; $DISTINCT / $LINES * 100"); COLUMN=$(head -1 Electric_Vehicle_Population_Data.csv | cut -d\; -f15); printf "%-50s %10d %11.3f \n" $COLUMN $DISTINCT $PERCENT 
DISTINCT=$(cut -d\; -f16 Electric_Vehicle_Population_Data.csv | sort | uniq | wc -l  );PERCENT=$(bc <<< "scale=4; $DISTINCT / $LINES * 100"); COLUMN=$(head -1 Electric_Vehicle_Population_Data.csv | cut -d\; -f16); printf "%-50s %10d %11.3f \n" $COLUMN $DISTINCT $PERCENT 
DISTINCT=$(cut -d\; -f17 Electric_Vehicle_Population_Data.csv | sort | uniq | wc -l  );PERCENT=$(bc <<< "scale=4; $DISTINCT / $LINES * 100"); COLUMN=$(head -1 Electric_Vehicle_Population_Data.csv | cut -d\; -f17); printf "%-50s %10d %11.3f \n" $COLUMN $DISTINCT $PERCENT 

